wpengine/phpcompat

wpengine-phpcompat.php

Check user capabilities for ajax calls.

---

wpengine-phpcompat.php

Another recommendation from @danielbachhuber! What do you think?

Use manage_options for ajax calls instead of edit_posts.

---

wpengine-phpcompat.php

Don't show error/warning badges if they don't exist.  

---

.travis.yml
Gruntfile.js
readme.md

Continuous Integration.

---

src/js/run.js
tests/qunit/test-run.js

This PR adds an overview of failed plugins for a scan. 
These stats are only shown if there is a failure. 
Resolves #17.

PHP-185 - Display stats for results. 

---

src/css/style.css
src/js/run.js
src/wpephpcompat.php
tests/qunit/test-run.js
wpengine-phpcompat.php

* You can now leave and revisit the test while in progress
* Displays current test running in progressbar status

[PHP-160] Allow leaving the test page during the scan.

---

.travis.yml
package.json
tests/qunit/helpers.js
tests/qunit/test-run.js

We should know when the JavaScript tests break too.

Run QUnit tests on Travis CI.  

---

readme.txt
src/js/run.js
wpengine-phpcompat.php

We should rely on built-in functionality to help us send and parse JSON. 
Resolves #52. 
Resolves #53, and possibly #31.

Use wp_send_json and let jQuery handle JSON.parse. 

---

src/js/run.js

Related to #56. Currently if a test gets stuck, there's no way to restart it. This PR allows you to hit the Re-run button when a test is in progress.

PHP-207 - Allow restarting an in progress test.

---

src/js/run.js
src/wpephpcompat.php
tests/qunit/helpers.js
wpengine-phpcompat.php

Add translation support

---

Gruntfile.js
composer.json
composer.lock
package.json
src/ruleset-wordpress.xml
src/wpcli.php
src/wpephpcompat.php
wpengine-phpcompat.php

Run php linting and phpcs on `npm test`.

Lint PHP and check code style automatically. 

---

composer.json
composer.lock
wpengine-phpcompat.php

Update to the latest version of the PHP Compatibility library and fix the install scripts.

Update to the latest version of the PHP Compatibility library.

---

src/wpephpcompat.php

More info on https://wordpress.org/support/topic/php-noticescommand-line-checkings/

Improvement of cli detection

---

src/wpephpcompat.php
tests/phpunit/test_generate_ignored_list.php
tests/phpunit/test_scan.php

This PR whitelists a number of plugins, and adds the ability to filter the whitelist. 
Resolves #89.
Resolves #85.
Resolves #84.
Resolves #76.

Whitelist updates.

---

src/css/style.css
src/js/run.js
src/wpcli.php
uninstall.php
wpengine-phpcompat.php

This PR adds a button that will delete all data from the database. 
Resolves #92.

Add a button to clean up data.

---

src/wpephpcompat.php

Adding Give to whitelist

---

.travis.yml

Fixes this issue: 
https://github.com/travis-ci/travis-ci/issues/8219

Add 5.2 and use dist: precise.

---

tests/phpunit/test_scan.php

added a test for PHP 7.2 scan

---

.travis.yml
package-lock.json
package.json
tests/phpunit/bootstrap.php

Update dependencies and pin to newer version

Update lodash and minimatch dependencies 

---

readme.md
readme.txt
wpengine-phpcompat.php

This pull request updates `readme.txt`, `readme.md`, and `wpengine-phpcompat.php` for version 1.5.1 release.

[NO-JIRA] Update for release 1.5.1

---

.circleci/config.yml
Dockerfile
composer.json
composer.lock
package-lock.json
src/wpephpcompat.php

This PR should clear up all errors with PHPCS so we can push out an update to fix the current php8 delete bug.

Updates package versions to be composer 2 compatible

---

.circleci/config.yml
readme.md
readme.txt
wpengine-phpcompat.php

This PR sets the next tagged version to fix PHP 8 incompatibility issues.

Prepares 1.5.2 Release

---

composer.json
composer.lock
package-lock.json
package.json

This pull request updates npm packages to fix vulnerability issues. Also added was an update to `composer.json` file to allow `phpcodesniffer-composer-installer` be enabled by default.

NPM package updates

---

package-lock.json

This addresses a moderate security issue in the css tooling.

Bump adobe/css-tools

---

package-lock.json
package.json

This PR bumps the WordPress core packages that include unsafe versions of the ip package. This has since been replaced in more recent versions hence the PR and bump.

Bumps core WordPress packages

---

package-lock.json
package.json

This PR bumps core packages and pins secure versions of buffer and mustache.

Bumps core packages

---

composer.lock
package-lock.json
package.json

This PR bumps symfony and cookie versions.

Bump symfony, cookie, and http-proxy-middleware

---

package-lock.json
package.json

Theres a new version of cross-spawn that we should bump

Bumps cross-spawn

---

package-lock.json
package.json

Fix https://wpengine.atlassian.net/jira/software/c/projects/ACF/boards/2253?selectedIssue=ACF-852

[ACF-852] - Bump babel core and preset -env to ^7.26

---

package-lock.json
package.json

This PR adds an npm override for webpack dev server to bump it to ^5.2.1.

Update webpack dev server

---

package-lock.json
package.json

This PR bumps the parent library of the Axios dependency and Brace Expansion.
└─┬ @wordpress/scripts@30.20.0
└─┬ jest-dev-server@10.1.4
└─┬ wait-on@8.0.1
└── axios@1.12.0

Bump Axios and Brace Expansion libraries. 
