- src/wpephpcompat.php
Fixes #24
Both are used for development. Neither are actual plugin / theme code.
> Excludes node_modules and tmp directories

- src/wpephpcompat.php
Reported here: 
https://wordpress.org/support/topic/only-scan-active-plugins-and-themes-scans-child-theme-but-not-parent-theme
If only scan active plugins is selected and you're using a child theme, the parent theme doesn't get scanned. This could be an issue since the parent theme's code could get executed. 
**Reviewer** 
**Screenshot**
> PHP-184 - Add the parent theme if the current theme is a child.

- src/wpcli.php
As reported here: 
https://wordpress.org/support/topic/error-invalid-value-specified-for-positional-arg?replies=3
The WP-CLI command doesn't work for all versions of WP-CLI. Instead of using the new PHPDoc syntax, lets use add_command until we can figure out what's going on. 
This also includes a number of other improvements.
> PHP-178 - Use add_command instead of the PHPDoc syntax.

- src/wpephpcompat.php
- tests/phpunit/test_generate_ignored_list.php
This PR adds a way to whitelist plugins/themes for certain PHP versions. The idea is to test popular plugins manually and review the results and whitelist them as we go. The results can be found here: 
https://github.com/wpengine/phpcompat/wiki/Results
> PHP-188 - Whitelist certain plugins.

- readme.md
- readme.txt
- src/wpephpcompat.php
Currently the timeout for the scan is set to a minute and this is hardcoded. Instead we should make it so the timeout can be changed. This would allow users to either disable it, or manually update it to match their environment.
Related GitHub issue: #32
> PHP-194 - Make the scan timeout configurable.

- src/wpephpcompat.php
- wpengine-phpcompat.php
@stevenkword noticed that the plugin currently being scanned wouldn't always update on the results page. It turns out these get_posts calls would get different posts. Lets sort them so it's always the same!
> PHP-202 - Sort the queue so we get the same job.

- src/wpephpcompat.php
Sorry for mistake,
I just saw when I done copy/paste, it's copied wrong character. I saw it in last (today's) update when I checked code again. It's strange because travis checking is passed.
Sasa
> Improvement of cli detection - fixing apostrophe

- wpengine-phpcompat.php
Adding new PHP versions meant editing HTML, using an array makes more sense, included a filter.
> Versions array instead of hardcoded HTML

- composer.json
- composer.lock
Updating the CodeSniffer version to 2.8.1. Tested this by creating a zip of this plugin and testing on my comp account against a few plugins.
> Update CodeSniffer version to 2.8.1

- .travis.yml
- package.json
A package included by phantomjs requires newer Node.js features, so we need to update Node.js in Travis. Apparently Grunt is no longer installed globally either (which is for the best), so I added the grunt-cli package. This should resolve the build issues! 
cc: @stevenkword
> Update Node in Travis. 

- src/wpephpcompat.php
This commit addresses concerns regarding warnings being thrown by the Genesis Framework about using double underscore prefixes on function names as reported in https://github.com/wpengine/phpcompat/issues/127 
I don't see a dev branch so please let me know if I need to change the branch to merge into. I've confirmed that Genesis (up to 2.7.0-dev) works on PHP 7.2.
> Add Genesis to Whitelist

- readme.md
- readme.txt
The PHP version statistics in `readme.txt` and `readme.md` were pretty outdated. This PR updates them, and also adds a link to the [official PHP supported versions page](https://secure.php.net/supported-versions.php)
> Update PHP versions statistics in readme files

- src/wpephpcompat.php
Fixes #178 
https://github.com/wpengine/phpcompat/issues/178
I'm the developer of the plugin, the lines in question are for backwards compatibility though PHP version 5.2. Confirmed working through 7.3 on hundreds of thousands of sites.
> Whitelist WPMU DEV Dashboard plugin

- .travis.yml
- tests/phpunit/bootstrap.php
Addresses dependency issues to fix master build
> Fix master build

- .travis.yml
- composer.json
- composer.lock
- php52/composer.lock
- readme.md
- readme.txt
- src/wpcli.php
- wpengine-phpcompat.php
This pull request adds support for checking code for compatibility with PHP 7.3.  Note: The option to check against PHP 7.3 will only appear if the server is running on PHP 5.3 or greater.
> Add PHP 7.3 Compatability Checks

- .travis.yml
- Gruntfile.js
- composer.json
- package-lock.json
- package.json
This pull request replaces the outdated [grunt-phpcs](https://www.npmjs.com/package/grunt-phpcs) with a composer phpcs command.
The grunt-phpcs package has not been updated in over 5 years and was setting off github security alarms due to outdated dependencies.
The new composer command `composer phpcs` wraps `vendor/bin/phpcs --standard=src/ruleset-wordpress.xml wpengine-phpcompat.php load-files.php src/*.php` command. This will analyze the same files with the same ruleset as a phpcs grunt script.
In addition, a `composer phpcs:fix` command was also added for fixable code sniffer errors. It wraps the `vendor/bin/phpcbf --standard=src/ruleset-wordpress.xml wpengine-phpcompat.php load-files.php src/*.php` command.
**Note: The `composer phpcs` command will not be ran in Travis for php 5.2. …
> [PI-3451] Replace grunt-phpcs with phpcs composer command.

- .travis.yml
This pull request moves the `bash php-lint.sh` command in the Travis config to run lint on all versions of php.
> Updated Travis to run php lint on all php versions.

- .phplint.yml
- .travis.yml
- Gruntfile.js
- composer.json
- composer.lock
- package-lock.json
- package.json
- php-lint.sh
This pull request removes two npm packages which have security warnings; [grunt-phpcs](https://www.npmjs.com/package/grunt-phpcs) and [grunt-phplint](https://www.npmjs.com/package/grunt-phplint). Both of these npm packages have not been updated in 3+ years.
`grunt-phpcs` was replaced by a composer command `composer phpcs`. This can be cleaned up in the future if needed.
`grunt-phplint` was replaced by a bash script [php-lint.sh](https://github.com/wpengine/phpcompat/blob/ryanmeier/feature/npm-security-updates/php-lint.sh). A bash script was used due to current available composer packages requiring php 7.2 and greater or have been abandoned. This made the current Travis build messy. In the future a composer package could be used as the php requirements change.
Also, thank you to @jrfnl for …
> NPM Security Updates

- package-lock.json
- package.json
All NPM packages (development) have been updated to their latest release. The old packages were constantly causing security notifications due to be so old.
Updated:
- `grunt` from `^0.4.5` to `^1.1.0`.
- `grunt-cli` from `^1.2.0` to `^1.3.2`.
- `node-qunit-phantomjs` from `^1.4.0` to `^2.1.1`.
Removed:
- `lodash` (Previously pinned for security patch.)
- `minimatch` (Previously pinned for security patch.)
```
npm ci
npm run test
npm run readme
```
> [NO-JIRA] Updated NPM Development Packages

- .circleci/config.yml
- .circleci/deploy.sh
This pull request adds the `deploy_job` to the `.circleci/config.yml` file for deploying a plugin release to the wordpress.org svn repository.
Also added was the `.circleci/deploy.sh` script for retrieving, building, and updating the plugin to it's wordpress.org svn repository.
**Note: The `deploy_job` cannot be triggered as of this moment due to it not being in the workflow yet.** 
Adding the `deploy_job` to the workflow will be in the next pull request.
> [PI-3517] Add Deployment Job and Script

- .circleci/config.yml
This pull request adds the `deploy_job` to the workflow in the `.circleci/config.yml` file. The `deploy_job` will be triggered when a release from Github is created. In order for the `deploy_job` to start, all other checks and tests jobs will need to pass successfully.
Documentation on releasing a new version the plugin will be added to the wiki shortly.
[PI-3518](https://wpengine.atlassian.net/browse/PI-3518)
> [PI-3518] Add deploy_job To CircleCI Workflow

- .circleci/config.yml
- .circleci/deploy.sh
This pull request updated the CircleCI `deploy.sh` file to sanitize tags that are not fully semver formatted. This was due to releases previously being released prefixed with a `v` character. The CircleCI config file was also adjusted to trigger if the `v` character was prefixed or not.
> [NO-JIRA] Update To Accommodate Prefixed Releases.

- src/wpephpcompat.php
SPM is getting false positive failures using the PHP Compatibility Checker. 
From Peter Mocko 
> This is the exact directory that we keep for backward compatibility with PHP5: 
wp-content/plugins/autoupdater/lib/vendor
> There are two packages that we use, that are also a part of WP core since some not old enough WP version - at least from SPM perspective
> paragonie/sodium_compat
> paragonie/random_compat
> 
From my understanding, we maintain a whitelist with a verified version that the plugin is compatible with. This PR mirrors that pattern using the SPM directory slug. Should be working with this. :)
> Adds whitelist entry for WP Engine SPM

- .github/CODEOWNERS
We need to add a codeowners file now that Blockheads owns this plugin. New days ahead for PHP Compatibility! It starts with ownership. Onward!
> adds codeowners file

- uninstall.php
Currently the plugin is unable to be deleted on PHP 8 environments. This is due to a number of out of date composer packages that have been held back from updating due to the restructure and loss of features it would entail. We are in progress on refactoring this entire plugin to be future proof, however, at the moment php 8 will remain incompatible with the current structure. This PR allows for php8 environments to delete the plugin without triggering the incompatible code.
To test this, you should be able to clone down the repo to the plugin directory, run composer install, npm install, and view the plugin on the plugins page of wp-admin to initiate a hopefully successful deletion.
> Fix: Removes initializing entire plugin class structure on delete

- package-lock.json
- package.json
This pull request pinned three npm packages to fix security vulnerabilities.
- `braces` to `^2.3.1`
- `chokidar` to `^3.5.3`
- `glob-parent` to `^5.1.2`
Also updated was `grunt` to version `^.1.5.2`
```
npm run test
```
```
npm run test:qunit
```
> Dependabot fixes and Grunt update

- package-lock.json
- package.json
It was noticed that the namespace was missing from the name which could get confusing to some folks. If this were ever published it would be under @ wpengine so we should probably reflect that in the name of this repo's package.json
> Adds namespace for package.json

- package-lock.json
- package.json
- plugin/wpengine-phpcompat.php
- readme.txt
- webpack.config.js
This fixes the issue with Tar versions by updating the terser-webpack-plugin which removes the dependency completely.
This does not require a deploy as these changes are already live on wordpress.org
> Fix tar dependency and bump versions

- package-lock.json
- package.json
This PR bumps wp-scripts to 30.8.0 which should resolve the express dependency (path-to-regexp)  flagged in ACF-745
> [ACF-745] - Update wp-scripts to 30.8.0
